remote_theme: jeffreytse/jekyll-theme-yat
title: My Articles
author: Luciano Pereira
email: your-email@domain.com
copyright: "lucianofullstack (c) 2023-{currentYear} {author}"
description: ""
yat:
  date_format: "%b %d, %Y"
