remote_theme: jeffreytse/jekyll-theme-yat
title: l u c i a n o  -  f u l l s t a c k
author: Luciano Pereira
email: lucianofullstack@duck.com
copyright: "lucianofullstack (c) 2023-{currentYear} {author}"
description: "lucianofullstack - This is my source code"
header_transparent: true
yat:
  date_format: "%b %d, %Y"
lang: "en"
translate_langs:
  - lang: en
    img: assets/flags/usa.png
    text: English
  - lang: es
    img: assets/flags/spain.png
    text: Spain
  - lang: it
    img: assets/flags/italy.png
    text: Italian
  - lang: de
    img: assets/flags/germany.png
    text: German
  - lang: pt
    img: assets/flags/portugal.png
    text: Portuguese
  - lang: fr
    img: assets/flags/france.png
    text: French
  - lang: ru
    img: assets/flags/russia.png     
    text: Russian
  - lang: hr
    img: assets/flags/croatia.png     
    text: Croatinan
  - lang: ar
    img: assets/flags/emirates.png
    text: Arab
  - lang: iw
    img: assets/flags/israel.png
    text: Hebrew
  - lang: zh-CN
    img: assets/flags/china.png
    text: Chinese
  - lang: ja
    img: assets/flags/japan.png
    text: Japanese
  - lang: ko
    img: assets/flags/korea.png
    text: Korean
