remote_theme: jeffreytse/jekyll-theme-yat
title: lucianofullstack
author: Luciano Pereira
email: lucianofullstack@duck.com
copyright: "lucianofullstack (c) 2023-{currentYear} {author}"
description: "lucianofullstack - This is my source code"
yat:
  date_format: "%b %d, %Y"
