remote_theme: jeffreytse/jekyll-theme-yat
title: l u c i a n o  -  f u l l s t a c k
author: Luciano Pereira
email: lucianofullstack@duck.com
copyright: "lucianofullstack (c) 2023-{currentYear} {author}"
description: "lucianofullstack - This is my source code"
header_transparent: true
yat:
  date_format: "%b %d, %Y"
lang: "en"
translate_langs:
  - lang: en
    img: assets/flags/usa.png
    text: English
  - lang: fr
    img: assets/france.png
    text: French
  - lang: ja
    img: assets/japan.png
    text: Japanese
