# Theme
remote_theme: jeffreytse/jekyll-theme-yat
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. https://example.com
# Config
title: design + code
author: Luciano Pereira
email: lucianofullstack@duck.com
description: "a blog about web development"
copyright: "design+code (c) {currentYear} {author}"
favicon: "https://lucianofullstack.github.io/articles/favicon.ico"
defaults:
    home:
        heading: "design➕code"
        subheading: "✒️ about web development"
        banner: "assets/banners/olivetti.jpg"
header_pages:
   - index.html
   - about.html
   - categories.html
   - tags.html
   - archives.html
# Design
theme_color: "#f2f8f0"
brand_color: "#ff7747"
code_badge:
    enabled: "true"
    color: "#fff"
    background_color: "#ff4e00"
    text_transform: "uppercase"
header_transparent: true
sitemap: false
night_mode: "auto"
content_width: "920px"
excerpt_size: 200
paginate: 5
yat:
  date_format: "%b %d, %Y"
# Language
lang: "en"
translate_langs:
  - lang: en
    img: assets/flags/usa.png
    text: English
  - lang: es
    img: assets/flags/spain.png
    text: Spain
  - lang: it
    img: assets/flags/italy.png
    text: Italian
  - lang: de
    img: assets/flags/germany.png
    text: German
  - lang: pt
    img: assets/flags/portugal.png
    text: Portuguese
  - lang: fr
    img: assets/flags/france.png
    text: French
  - lang: ru
    img: assets/flags/russia.png     
    text: Russian
  - lang: hr
    img: assets/flags/croatia.png     
    text: Croatinan
  - lang: ar
    img: assets/flags/emirates.png
    text: Arab
  - lang: iw
    img: assets/flags/israel.png
    text: Hebrew
  - lang: zh-CN
    img: assets/flags/china.png
    text: Chinese
  - lang: ja
    img: assets/flags/japan.png
    text: Japanese
  - lang: ko
    img: assets/flags/korea.png
    text: Korean
# Comments
utterances:
    repo: "lucianofullstack/comments"
    issue_term: "title"
    label: "utterances comment"
    theme: "github-light"
    follow_site_theme: true
# Analytics
# google_analytics: "G-2RN9JC9F2K"
# highlighter: rouge
markdown: kramdown
kmarkdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
