# Theme
remote_theme: jeffreytse/jekyll-theme-yat
# Config
title: l u c i a n o  -  f u l l s t a c k
author: Luciano Pereira
email: lucianofullstack@duck.com
copyright: "lucianofullstack (c) 2023-{currentYear} {author}"
description: "lucianofullstack - This is my source code"
favicon: "https://lucianofullstack.github.io/articles/favicon.ico"
defaults:
    home:
        heading: "Your awesome heading"
        subheading: "Your awesome subheading"
header_pages:
   - index.html
   - about.md
# Design
theme_color: "#0000FF"
brand_color: "#00FF00"
header_transparent: true
sitemap: false
night_mode: "auto"
content_width: "920px"
excerpt_size: 350
paginate: 5
yat:
  date_format: "%b %d, %Y"
# Language
lang: "en"
translate_langs:
  - lang: en
    img: assets/flags/usa.png
    text: English
  - lang: es
    img: assets/flags/spain.png
    text: Spain
  - lang: it
    img: assets/flags/italy.png
    text: Italian
  - lang: de
    img: assets/flags/germany.png
    text: German
  - lang: pt
    img: assets/flags/portugal.png
    text: Portuguese
  - lang: fr
    img: assets/flags/france.png
    text: French
  - lang: ru
    img: assets/flags/russia.png     
    text: Russian
  - lang: hr
    img: assets/flags/croatia.png     
    text: Croatinan
  - lang: ar
    img: assets/flags/emirates.png
    text: Arab
  - lang: iw
    img: assets/flags/israel.png
    text: Hebrew
  - lang: zh-CN
    img: assets/flags/china.png
    text: Chinese
  - lang: ja
    img: assets/flags/japan.png
    text: Japanese
  - lang: ko
    img: assets/flags/korea.png
    text: Korean
# Comments
utterances:
    repo: "lucianofullstack/comments"
    issue_term: "title"
    label: "utterances comment"
    theme: "github-light"
    follow_site_theme: true
# Analytics
google_analytics: "G-2RN9JC9F2K"
